name: graphql_cli
description: Command line tool for conmon GraphQL development workflows.
version: 0.0.1
repository: https://github.com/ricardodalarme/graphql-cli
issue_tracker: https://github.com/ricardodalarme/graphql-cli/issues
homepage: https://github.com/ricardodalarme/graphql-cli

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
